[package]
name = "del-raycast"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
num-traits = "0.2.19"
image = "0.25.5"
anyhow = "1.0.93"
ply-rs = "0.1.3"
arrayref = "0.3.9"
slice-of-array = "0.3.2"

# for development
pbrt4 = { path = "../pbrt4" }
del-geo-nalgebra = { path="../del-geo/del-geo-nalgebra" }
del-msh-core = { path = "../del-msh/del-msh-core" }
del-geo-core = { path = "../del-geo/del-geo-core" }

# for git push
# pbrt4 = { git = "https://github.com/nobuyuki83/pbrt4.git" }
