[package]
name = "del-raycast"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
rand = "0.8.5"
num-traits = "0.2.19"
image = "0.25.4"
anyhow = "1.0.92"
regex = "1.11.1"

# del-* library
del-geo-nalgebra = { path="../del-geo/del-geo-nalgebra" }
del-msh-core = { path = "../del-msh/del-msh-core" }
del-geo-core = { path = "../del-geo/del-geo-core" }